name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 把分支拉出来
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 指定node版本
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1

      # 安装依赖
      - name: Install
        run: |
          npm install

      # 执行 semantic-release 发布包
      - name: Release NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        with:
          registry-url: https://registry.npmjs.org/

      - name: Release Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        with:
          registry-url: https://npm.pkg.github.com/
